import 'package:flutter/material.dart';

import 'models.dart';

const Map<ToeicLevel, List<Word>> toeicWordsByLevel = {
  ToeicLevel.none: [
    Word('hello', '안녕'),
    Word('thank you', '감사합니다'),
    Word('please', '부탁합니다'),
    Word('sorry', '죄송합니다'),
    Word('yes', '예'),
    Word('no', '아니오'),
    Word('day', '날, 하루'),
    Word('time', '시간'),
    Word('work', '일하다'),
    Word('home', '집'),
    Word('book', '책'),
    Word('phone', '전화'),
    Word('name', '이름'),
    Word('year', '년, 해'),
    Word('month', '월, 달'),
    Word('week', '주'),
    Word('today', '오늘'),
    Word('tomorrow', '내일'),
    Word('yesterday', '어제'),
    Word('morning', '아침'),
    Word('evening', '저녁'),
    Word('food', '음식'),
    Word('water', '물'),
    Word('money', '돈'),
    Word('friend', '친구'),
  ],
  ToeicLevel.lv200: [
    Word('office', '사무실'),
    Word('meeting', '회의'),
    Word('email', '이메일'),
    Word('letter', '편지'),
    Word('order', '주문'),
    Word('product', '제품'),
    Word('price', '가격'),
    Word('service', '서비스'),
    Word('customer', '고객'),
    Word('manager', '관리자'),
    Word('report', '보고서'),
    Word('plan', '계획'),
    Word('company', '회사'),
    Word('business', '사업'),
    Word('job', '일자리'),
    Word('team', '팀'),
    Word('project', '프로젝트'),
    Word('document', '문서'),
    Word('file', '파일'),
    Word('copy', '사본, 복사하다'),
    Word('print', '인쇄하다'),
    Word('send', '보내다'),
    Word('receive', '받다'),
    Word('check', '확인하다'),
    Word('sign', '서명하다'),
  ],
  ToeicLevel.lv500: [
    Word('schedule', '일정'),
    Word('appointment', '약속'),
    Word('invoice', '청구서'),
    Word('payment', '지불'),
    Word('discount', '할인'),
    Word('refund', '환불'),
    Word('warranty', '보증'),
    Word('shipment', '배송'),
    Word('contract', '계약'),
    Word('department', '부서'),
    Word('budget', '예산'),
    Word('revenue', '수익'),
    Word('deadline', '마감 기한'),
    Word('agenda', '안건'),
    Word('proposal', '제안서'),
    Word('negotiate', '협상하다'),
    Word('supplier', '공급업체'),
    Word('vendor', '판매업체'),
    Word('retail', '소매'),
    Word('wholesale', '도매'),
    Word('expense', '경비'),
    Word('profit', '이익'),
    Word('loss', '손실'),
    Word('branch', '지점'),
    Word('headquarters', '본사'),
  ],
  ToeicLevel.lv700: [
    Word('quarterly', '분기별의'),
    Word('expenditure', '지출'),
    Word('procurement', '조달'),
    Word('inventory', '재고'),
    Word('logistics', '물류'),
    Word('compliance', '준수'),
    Word('benchmark', '기준점'),
    Word('forecast', '예측'),
    Word('subsidiary', '자회사'),
    Word('acquisition', '인수'),
    Word('liability', '부채'),
    Word('overhead', '간접비'),
    Word('stakeholder', '이해관계자'),
    Word('shareholder', '주주'),
    Word('dividend', '배당금'),
    Word('equity', '자기자본'),
    Word('capital', '자본'),
    Word('asset', '자산'),
    Word('allocation', '할당'),
    Word('audit', '감사'),
    Word('fiscal', '재정의'),
    Word('merger', '합병'),
    Word('restructure', '구조조정하다'),
    Word('outsource', '외주를 주다'),
    Word('quota', '할당량'),
  ],
  ToeicLevel.lv989: [
    Word('discrepancy', '불일치'),
    Word('contingency', '비상사태'),
    Word('amortization', '상각'),
    Word('liquidation', '청산'),
    Word('depreciation', '감가상각'),
    Word('arbitration', '중재'),
    Word('jurisdiction', '관할권'),
    Word('proprietary', '독점적인'),
    Word('reimbursement', '상환'),
    Word('indemnify', '배상하다'),
    Word('stipulate', '규정하다'),
    Word('mitigate', '완화하다'),
    Word('leverage', '영향력, 차입금'),
    Word('hedge', '회피하다'),
    Word('derivative', '파생상품'),
    Word('divestiture', '매각'),
    Word('consolidate', '통합하다'),
    Word('prevailing', '우세한'),
    Word('scrutinize', '면밀히 조사하다'),
    Word('deflation', '디플레이션'),
    Word('encumbrance', '부담, 저당'),
    Word('fiduciary', '수탁자의'),
    Word('ratify', '비준하다'),
    Word('expedite', '신속히 처리하다'),
    Word('contingent', '불확정적인'),
  ],
};

const List<Category> englishCategories = [
  Category(
    id: 'basic',
    name: '기초',
    description: '입문자를 위한 기본 단어',
    icon: Icons.school,
    words: [
      Word('apple', '사과'),
      Word('water', '물'),
      Word('book', '책'),
      Word('house', '집'),
      Word('friend', '친구'),
      Word('school', '학교'),
      Word('food', '음식'),
      Word('family', '가족'),
      Word('happy', '행복한'),
      Word('time', '시간'),
      Word('car', '자동차'),
      Word('dog', '개'),
      Word('cat', '고양이'),
      Word('tree', '나무'),
      Word('flower', '꽃'),
      Word('sun', '해'),
      Word('moon', '달'),
      Word('day', '낮, 하루'),
      Word('night', '밤'),
      Word('baby', '아기'),
      Word('mother', '어머니'),
      Word('father', '아버지'),
      Word('sister', '여자 형제'),
      Word('brother', '남자 형제'),
      Word('hand', '손'),
      Word('foot', '발'),
      Word('eye', '눈'),
      Word('mouth', '입'),
      Word('head', '머리'),
      Word('milk', '우유'),
    ],
  ),
  Category(
    id: 'conversation',
    name: '회화',
    description: '일상 대화 표현',
    icon: Icons.chat_bubble_outline,
    words: [
      Word('hello', '안녕하세요'),
      Word('thanks', '고마워요'),
      Word('sorry', '미안해요'),
      Word('please', '부탁해요'),
      Word('welcome', '환영해요'),
      Word('goodbye', '잘 가요'),
      Word('excuse me', '실례합니다'),
      Word('no problem', '문제없어요'),
      Word('of course', '물론이죠'),
      Word('see you', '또 봐요'),
      Word('how are you', '어떻게 지내요'),
      Word('nice to meet you', '만나서 반가워요'),
      Word('take care', '몸 조심해요'),
      Word('good morning', '좋은 아침'),
      Word('good night', '잘 자요'),
      Word('never mind', '신경 쓰지 마세요'),
      Word('my pleasure', '천만에요'),
      Word('congratulations', '축하해요'),
      Word('good luck', '행운을 빌어요'),
      Word('cheers', '건배'),
      Word('by the way', '그런데'),
      Word('I think so', '그런 것 같아요'),
      Word('that is right', '맞아요'),
      Word('well done', '잘했어요'),
      Word('no way', '말도 안 돼'),
      Word('let me see', '어디 보자'),
      Word('just kidding', '농담이에요'),
      Word('any time', '언제든지요'),
      Word('me too', '저도요'),
      Word('hold on', '잠시만요'),
    ],
  ),
  Category(
    id: 'toeic',
    name: 'TOEIC',
    description: '점수대별 비즈니스 영어',
    icon: Icons.business_center,
    words: [],
  ),
  Category(
    id: 'toefl',
    name: 'TOEFL',
    description: '학술 영어',
    icon: Icons.menu_book,
    words: [
      Word('analyze', '분석하다'),
      Word('hypothesis', '가설'),
      Word('theory', '이론'),
      Word('research', '연구'),
      Word('conclusion', '결론'),
      Word('evidence', '증거'),
      Word('evaluate', '평가하다'),
      Word('perspective', '관점'),
      Word('significant', '중요한'),
      Word('comprehensive', '포괄적인'),
      Word('methodology', '방법론'),
      Word('paradigm', '패러다임'),
      Word('phenomenon', '현상'),
      Word('empirical', '경험적인'),
      Word('synthesize', '종합하다'),
      Word('interpret', '해석하다'),
      Word('infer', '추론하다'),
      Word('derive', '도출하다'),
      Word('demonstrate', '입증하다'),
      Word('examine', '검토하다'),
      Word('contrast', '대조하다'),
      Word('illustrate', '설명하다'),
      Word('justify', '정당화하다'),
      Word('contradict', '모순되다'),
      Word('validate', '검증하다'),
      Word('refute', '반박하다'),
      Word('fundamental', '근본적인'),
      Word('concept', '개념'),
      Word('framework', '틀, 체계'),
      Word('premise', '전제'),
    ],
  ),
  Category(
    id: 'ielts',
    name: 'IELTS',
    description: '국제 영어 시험',
    icon: Icons.public,
    words: [
      Word('environment', '환경'),
      Word('sustainable', '지속 가능한'),
      Word('economy', '경제'),
      Word('culture', '문화'),
      Word('education', '교육'),
      Word('technology', '기술'),
      Word('immigration', '이민'),
      Word('globalization', '세계화'),
      Word('infrastructure', '기반시설'),
      Word('democracy', '민주주의'),
      Word('poverty', '빈곤'),
      Word('urbanization', '도시화'),
      Word('biodiversity', '생물 다양성'),
      Word('renewable', '재생 가능한'),
      Word('pollution', '오염'),
      Word('climate', '기후'),
      Word('agriculture', '농업'),
      Word('transportation', '교통, 운송'),
      Word('communication', '의사소통'),
      Word('healthcare', '의료'),
      Word('employment', '고용'),
      Word('inflation', '인플레이션'),
      Word('recession', '경기 침체'),
      Word('inequality', '불평등'),
      Word('diversity', '다양성'),
      Word('innovation', '혁신'),
      Word('productivity', '생산성'),
      Word('regulation', '규제'),
      Word('legislation', '법률'),
      Word('welfare', '복지'),
    ],
  ),
  Category(
    id: 'csat',
    name: '수능',
    description: '대학수학능력시험',
    icon: Icons.edit_note,
    words: [
      Word('abandon', '버리다'),
      Word('abstract', '추상적인'),
      Word('accomplish', '성취하다'),
      Word('acquire', '얻다'),
      Word('adapt', '적응하다'),
      Word('adequate', '적절한'),
      Word('advocate', '옹호하다'),
      Word('anxiety', '불안'),
      Word('approach', '접근하다'),
      Word('assume', '가정하다'),
      Word('capable', '능력 있는'),
      Word('comprehend', '이해하다'),
      Word('concentrate', '집중하다'),
      Word('consist', '구성되다'),
      Word('constant', '끊임없는'),
      Word('contribute', '기여하다'),
      Word('convince', '확신시키다'),
      Word('decline', '감소하다'),
      Word('declare', '선언하다'),
      Word('depend', '의존하다'),
      Word('describe', '묘사하다'),
      Word('devote', '헌신하다'),
      Word('distinguish', '구별하다'),
      Word('emphasize', '강조하다'),
      Word('encounter', '마주치다'),
      Word('enhance', '향상시키다'),
      Word('establish', '설립하다'),
      Word('estimate', '추정하다'),
      Word('observe', '관찰하다'),
      Word('recognize', '인식하다'),
    ],
  ),
];

const List<Language> languages = [
  Language(
    code: 'en',
    name: '영어',
    flag: '🇺🇸',
    categories: englishCategories,
  ),
  Language(
    code: 'ja',
    name: '일본어',
    flag: '🇯🇵',
    categories: [],
    available: false,
  ),
  Language(
    code: 'zh',
    name: '중국어',
    flag: '🇨🇳',
    categories: [],
    available: false,
  ),
];
